#ifndef VULKAN_MACROS_H
#define VULKAN_MACROS_H

#include "VRVulkan.h"
#include "VRDefine.h"

#define VK_REQUIRED_VERSION_MAJOR  1
#define VK_REQUIRED_VERSION_MINOR  0
#define VK_MAX_COMMAND_BUFFERS  3
#define VK_MAX_PIPELINE_AGE 5

#define SWAP_CHAIN_CONFIG_TRANSPARENT 0x1
#define SWAP_CHAIN_CONFIG_READABLE 0x2
#define SWAP_CHAIN_CONFIG_ENABLE_XCB 0x4
#define SWAP_CHAIN_CONFIG_APPLE_CVPIXELBUFFER 0x8
#define MAX_VERTEX_ATTRIBUTE_COUNT 16
#define MAX_SAMPLER_COUNT 16
#define MAX_VERTEX_BUFFER_COUNT 16
#define CONFIG_BINDING_COUNT 8

#define MIN_SUPPORTED_RENDER_TARGET_COUNT 4
#define MAX_SUPPORTED_RENDER_TARGET_COUNT 4

#define BINDING_COUNT 16
#define SHADER_TYPE_COUNT 2

#define UBUFFER_BINDING_COUNT BINDING_COUNT
#define SAMPLER_BINDING_COUNT MAX_SAMPLER_COUNT
#define TARGET_BINDING_COUNT MAX_SUPPORTED_RENDER_TARGET_COUNT
#define SHADER_MODULE_COUNT SHADER_TYPE_COUNT
#define VERTEX_ATTRIBUTE_COUNT  MAX_VERTEX_ATTRIBUTE_COUNT

#ifdef VR_VULKAN_SUPPORT_MULTIPASS
#define DESCRIPTOR_TYPE_COUNT 3 // uniforms, combined image samplers, and input attachments
#else
#define DESCRIPTOR_TYPE_COUNT 2 // uniforms, combined image samplers
#endif
 
#endif // VULKAN_MACROS_H
